export const moviesMock = [
	{
		id: 1,
		title: 'Интерстеллар',
		rating: 8.6,
		image: '/interstellar.jpg',
		category: 'Sci-Fi',
	},
	{
		id: 2,
		title: 'Начало',
		rating: 8.8,
		image: '/film1920x.webp',
		category: 'Thriller',
	},
	{
		id: 3,
		title: 'Побег из Шоушенка',
		rating: 9.3,
		image: '/shawshank.jpeg',
		category: 'Drama',
	},
	{
		id: 4,
		title: 'Интерстеллар',
		rating: 8.6,
		image: '/interstellar.jpg',
		category: 'Sci-Fi',
	},
	{
		id: 5,
		title: 'Начало',
		rating: 8.8,
		image: '/film1920x.webp',
		category: 'Thriller',
	},
	{
		id: 6,
		title: 'Побег из Шоушенка',
		rating: 9.3,
		image: '/shawshank.jpeg',
		category: 'Drama',
	},
	{
		id: 7,
		title: 'Интерстеллар',
		rating: 8.6,
		image: '/interstellar.jpg',
		category: 'Sci-Fi',
	},
	{
		id: 8,
		title: 'Начало',
		rating: 8.8,
		image: '/film1920x.webp',
		category: 'Thriller',
	},
	{
		id: 9,
		title: 'Побег из Шоушенка',
		rating: 9.3,
		image: '/shawshank.jpeg',
		category: 'Drama',
	},
];
